'\" t
.\"     Title: 
      ags
    
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2015-06-15
.\"    Manual: ags v0.4.2
.\"    Source: ags v0.4.2
.\"  Language: English
.\"
.TH "AGS" "1" "2015\-06\-15" "ags v0.4.2" "ags v0.4.2"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ags \- Advanced Gtk+ Sequencer is an audio sequencer and composition editor
.SH "SYNOPSIS"
.HP \w'\fB/usr/bin/ags\fR\ 'u
\fB/usr/bin/ags\fR [\-\-help] [\-\-version] [\-\-single\-thread] [\-\-filename\ \fIfile\fR...]
.SH "DESCRIPTION"
.PP
Advanced GTK+ Sequencer is intended to use for music composition\&. It features a piano roll, as well a synth, matrix editor, drum machine, soundfont2 player, mixer and an output panel\&. It\(cqs designed to be highly configurable\&. You may add effects to its effect chain; and add or remove audio channels/pads\&. You may set up a fully functional network of engines, thus there is a link editor for linking audio lines\&.
.PP
LADSPA support has been added to version 0\&.4\&.2 as well export to WAV audio file\&.
.PP
\&...
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, with long options starting with two dashes (`\-\*(Aq)\&. A summary of options is included below\&. For a complete description, see the
\fBinfo\fR(1)
files\&.
.PP
\fB\-\-filename file\fR
.RS 4
Open file from command line\&.
.RE
.PP
\fB\-\-single\-thread\fR
.RS 4
Run in single thread mode\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Show version of program\&.
.RE
.SH "BUGS"
.PP
None\&. So far I know\&.
.SH "AUTHOR"
.PP
Joël Krähemann
