FROM ghcr.io/gsequencer/msys2
RUN bash -c "git clone https://github.com/gsequencer/gsequencer.git"
RUN bash -c "git clone git://git.sv.gnu.org/gnulib.git"
RUN bash -c "wget -c http://xn--krhemann-1za.com/download/ags-user-manual.pdf"
RUN bash -c "cd gsequencer && ../gnulib/gnulib-tool --import langinfo regex signal-h sigaction strings sys_types memcpy"
RUN bash -c "cd gsequencer && rm -f configure.ac Makefile.am && cp configure.ac-win32 configure.ac && Makefile.am-win32 Makefile.am"
RUN bash -c "cd gsequencer && autoreconf -fi && PATH=/bin:/usr/bin:/mingw64/bin:/mingw64/x86_64/bin PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig CPATH=/mingw64/include ./configure --host=x86_64-w64-mingw32 --prefix=/mingw64 --disable-rt --enable-w32api --disable-alsa --disable-jack --disable-pulse --enable-wasapi --disable-x11 --without-webkit --with-poppler && make"
RUN bash -c "cd gsequencer && make install"
RUN bash -c "mkdir -v -p ./GSequencer-$GSEQUENCER_VERSION-x86_64/{LV2,dssi,etc,ladspa,lib,libexec,share}"
RUN bash -c "mkdir -v -p ./GSequencer-$GSEQUENCER_VERSION-x86_64/share/doc/gsequencer-doc/pdf/"
RUN bash -c "cp -a -v /mingw64/libexec ./GSequencer-$VERSION-x86_64/"
RUN bash -c "cp -a -v /mingw64/etc ./GSequencer-$GSEQUENCER_VERSION-x86_64/"
RUN bash -c "cp -a -v /mingw64/lib ./GSequencer-$GSEQUENCER_VERSION-x86_64/"
RUN bash -c "cp -a -v /mingw64/share ./GSequencer-$GSEQUENCER_VERSION-x86_64/"
RUN bash -c "cp -a -v /mingw64/bin/{gsequencer,midi2xml}.exe ./GSequencer-$GSEQUENCER_VERSION-x86_64/"
RUN bash -c "cp -a -v /mingw64/bin/*.dll ./GSequencer-$GSEQUENCER_VERSION-x86_64/"
RUN bash -c "cp -a -v ags-user-manual.pdf ./GSequencer-$GSEQUENCER_VERSION-x86_64/share/doc/gsequencer-doc/pdf/"
RUN bash -c "zip -r GSequencer-$VERSION-x86_64.zip GSequencer-$GSEQUENCER_VERSION-x86_64"
