#!/bin/sh
set -e

dpkg-source --before-build `pwd`
dpkg-buildpackage -rfakeroot --target=pre-integration-test
export HOST=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

if [ -d "/usr/lib/gsequencer" ]
then
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/lib/gsequencer
elif [ -d "/usr/lib/$HOST/gsequencer" ]
then
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/lib/$HOST/gsequencer
fi

xvfb-run --server-args="-screen 0 1920x1080x24" make ags-integration-test
