ags_indicator_test: ags_indicator_test.c ../../widget/ags_indicator.c
	gcc -g -o ags_indicator_test ags_indicator_test.c ../../widget/ags_indicator.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_remove_indicator_test: ags_remove_indicator_test.c ../../widget/ags_remove_indicator.c
	gcc -g -o ags_remove_indicator_test ags_remove_indicator_test.c ../../widget/ags_indicator.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_cartesian_test: ags_cartesian_test.c ../../widget/ags_cartesian.c
	gcc -g -o ags_cartesian_test ags_cartesian_test.c ../../widget/ags_cartesian.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_dial_test: ags_dial_test.c ../../widget/ags_dial.c
	gcc -g -o ags_dial_test ags_dial_test.c ../../widget/ags_dial.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_expander_set_test: ags_expander_set_test.c ../../widget/ags_expander_set.c
	gcc -g -o ags_expander_set_test ags_expander_set_test.c ../../widget/ags_expander_set.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_expander_test: ags_expander_test.c ../../widget/ags_expander.c
	gcc -g -o ags_expander_test ags_expander_test.c ../../widget/ags_expander.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_viewport_test: ags_viewport_test.c
	gcc -g -o ags_viewport_test ags_viewport_test.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_scrolled_level_box_test: ags_scrolled_level_box_test.c ../../widget/ags_scrolled_level_box.c ../../widget/ags_level_box.c ../../widget/ags_level.c ../../widget/ags_widget_marshal.c
	gcc -g -o ags_scrolled_level_box_test ags_scrolled_level_box_test.c ../../widget/ags_scrolled_level_box.c ../../widget/ags_level_box.c ../../widget/ags_level.c ../../widget/ags_widget_marshal.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_scrolled_scale_box_test: ags_scrolled_scale_box_test.c ../../widget/ags_scrolled_scale_box.c ../../widget/ags_scale_box.c ../../widget/ags_scale.c ../../widget/ags_widget_marshal.c
	gcc -g -o ags_scrolled_scale_box_test ags_scrolled_scale_box_test.c ../../widget/ags_scrolled_scale_box.c ../../widget/ags_scale_box.c ../../widget/ags_scale.c ../../widget/ags_widget_marshal.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_level_box_test: ags_level_box_test.c ../../widget/ags_level_box.c ../../widget/ags_level.c ../../widget/ags_widget_marshal.c
	gcc -g -o ags_level_box_test ags_level_box_test.c ../../widget/ags_level_box.c ../../widget/ags_level.c ../../widget/ags_widget_marshal.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_scale_box_test: ags_scale_box_test.c ../../widget/ags_scale_box.c ../../widget/ags_scale.c ../../widget/ags_widget_marshal.c
	gcc -g -o ags_scale_box_test ags_scale_box_test.c ../../widget/ags_scale_box.c ../../widget/ags_scale.c ../../widget/ags_widget_marshal.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_level_test: ags_level_test.c ../../widget/ags_level.c
	gcc -g -o ags_level_test ags_level_test.c ../../widget/ags_level.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_scale_test: ags_scale_test.c ../../widget/ags_scale.c
	gcc -g -o ags_scale_test ags_scale_test.c ../../widget/ags_scale.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_led_test: ags_led_test.c ../../widget/ags_led.c
	gcc -g -o ags_led_test ags_led_test.c ../../widget/ags_led.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_led_array_test: ags_led_array_test.c ../../widget/ags_led_array.c ../../widget/ags_led.c
	gcc -g -o ags_led_array_test ags_led_array_test.c ../../widget/ags_led_array.c ../../widget/ags_led.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_piano_test: ags_piano_test.c ../../widget/ags_piano.c ../../widget/ags_widget_marshal.c
	gcc -g -o ags_piano_test ags_piano_test.c ../../widget/ags_piano.c ../../widget/ags_widget_marshal.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_ruler_test: ags_ruler_test.c ../../widget/ags_ruler.c
	gcc -g -o ags_ruler_test ags_ruler_test.c ../../widget/ags_ruler.c -I../../.. `pkg-config --cflags --libs gtk4` -lm
