ags_indicator_test: ags_indicator_test.c ../../widget/ags_indicator.c
	gcc -g -o ags_indicator_test ags_indicator_test.c ../../widget/ags_indicator.c -I../../.. `pkg-config --cflags --libs gtk4`

ags_cartesian_test: ags_cartesian_test.c ../../widget/ags_cartesian.c
	gcc -g -o ags_cartesian_test ags_cartesian_test.c ../../widget/ags_cartesian.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_dial_test: ags_dial_test.c ../../widget/ags_dial.c
	gcc -g -o ags_dial_test ags_dial_test.c ../../widget/ags_dial.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_expander_set_test: ags_expander_set_test.c ../../widget/ags_expander_set.c
	gcc -g -o ags_expander_set_test ags_expander_set_test.c ../../widget/ags_expander_set.c -I../../.. `pkg-config --cflags --libs gtk4` -lm

ags_expander_test: ags_expander_test.c ../../widget/ags_expander.c
	gcc -g -o ags_expander_test ags_expander_test.c ../../widget/ags_expander.c -I../../.. `pkg-config --cflags --libs gtk4` -lm
