Document: ags
Title: Debian ags Manual
Author: <insert document author here>
Abstract: This manual describes what ags is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ags/ags.sgml.gz

Format: postscript
Files: /usr/share/doc/ags/ags.ps.gz

Format: text
Files: /usr/share/doc/ags/ags.text.gz

Format: HTML
Index: /usr/share/doc/ags/html/index.html
Files: /usr/share/doc/ags/html/*.html
