usr/lib/*/gsequencer/libgsequencer*
usr/bin
usr/share/gsequencer
usr/share/xml/gsequencer
usr/share/doc/gsequencer/README
usr/share/doc/gsequencer/ags_example.xml
usr/share/man
usr/share/applications
usr/share/doc/gsequencer/images/* usr/share/doc/gsequencer-doc/images/
usr/share/doc/gsequencer/html/* usr/share/doc/gsequencer-doc/html/
usr/lib/*/libags_gui.so.*
usr/lib/*/libags_gui.so
usr/lib/*/pkgconfig/libags_gui.pc
usr/include/ags/libags-gui.h
usr/include/ags/widget
usr/share/doc/libags-gui-doc/api/* usr/share/doc/libags-gui-doc/api/
usr/lib/*/libags_audio.so.*
usr/lib/*/libags_audio.so
usr/lib/*/pkgconfig/libags_audio.pc
usr/include/ags/libags-audio.h
usr/include/ags/plugin
usr/include/ags/audio
usr/share/doc/libags-audio-doc/images/* usr/share/doc/libags-audio-doc/images/
usr/share/doc/libags-audio-doc/html/* usr/share/doc/libags-audio-doc/html/
usr/share/doc/libags-audio-doc/osc-server/* usr/share/doc/libags-audio-doc/osc-server/
usr/share/doc/libags-audio-doc/api/* usr/share/doc/libags-audio-doc/api
usr/lib/*/libags.so.*
usr/lib/*/libags_thread.so.*
usr/lib/*/libags_server.so.*
usr/lib/*/libags.so
usr/lib/*/libags_thread.so
usr/lib/*/libags_server.so
usr/lib/*/pkgconfig/libags.pc
usr/include/ags/libags.h
usr/include/ags/util
usr/include/ags/lib
usr/include/ags/object
usr/include/ags/file
usr/include/ags/thread
usr/include/ags/server
usr/share/doc/libags-doc/api/* usr/share/doc/libags-doc/api/
