usr/lib/*/libgsequencer*
usr/bin/com.github.gsequencer.gsequencer
usr/bin/midi2xml
usr/share/gsequencer
usr/share/xml/gsequencer
usr/share/doc/gsequencer/README
usr/share/doc/gsequencer/ags_example.xml
usr/share/man
usr/share/applications/com.github.gsequencer.gsequencer.desktop
usr/share/metainfo/com.github.gsequencer.gsequencer.appdata.xml
usr/share/doc/gsequencer/images/* usr/share/doc/gsequencer-doc/images/
usr/share/doc/gsequencer/html/* usr/share/doc/gsequencer-doc/html/
usr/lib/*/libags_gui.so.*
usr/lib/*/libags_gui.so
usr/lib/*/libags_audio.so.*
usr/lib/*/libags_audio.so
usr/share/doc/libags-audio-doc/images/* usr/share/doc/libags-audio-doc/images/
usr/share/doc/libags-audio-doc/html/* usr/share/doc/libags-audio-doc/html/
usr/share/doc/libags-audio-doc/osc-server/* usr/share/doc/libags-audio-doc/osc-server/
usr/lib/*/libags.so.*
usr/lib/*/libags_thread.so.*
usr/lib/*/libags_server.so.*
usr/lib/*/libags.so
usr/lib/*/libags_thread.so
usr/lib/*/libags_server.so
