/* GSequencer - Advanced GTK Sequencer
 * Copyright (C) 2005-2022 Joël Krähemann
 *
 * This file is part of GSequencer.
 *
 * GSequencer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GSequencer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GSequencer.  If not, see <http://www.gnu.org/licenses/>.
 */
/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __AGS_CCLOSURE_MARSHAL_MARSHAL_H__
#define __AGS_CCLOSURE_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:UINT64 (ags/object/ags_marshallers.list:1) */
extern
void ags_cclosure_marshal_VOID__UINT64 (GClosure     *closure,
                                        GValue       *return_value,
                                        guint         n_param_values,
                                        const GValue *param_values,
                                        gpointer      invocation_hint,
                                        gpointer      marshal_data);

/* VOID:BOOLEAN,POINTER (ags/object/ags_marshallers.list:2) */
extern
void ags_cclosure_marshal_VOID__BOOLEAN_POINTER (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:INT,UINT (ags/object/ags_marshallers.list:3) */
extern
void ags_cclosure_marshal_VOID__INT_UINT (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);

/* VOID:INT,POINTER (ags/object/ags_marshallers.list:4) */
extern
void ags_cclosure_marshal_VOID__INT_POINTER (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* VOID:INT,UINT,POINTER (ags/object/ags_marshallers.list:5) */
extern
void ags_cclosure_marshal_VOID__INT_UINT_POINTER (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:UINT,BOOLEAN (ags/object/ags_marshallers.list:6) */
extern
void ags_cclosure_marshal_VOID__UINT_BOOLEAN (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* VOID:UINT,UINT (ags/object/ags_marshallers.list:7) */
extern
void ags_cclosure_marshal_VOID__UINT_UINT (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* VOID:UINT,UINT,BOOLEAN (ags/object/ags_marshallers.list:8) */
extern
void ags_cclosure_marshal_VOID__UINT_UINT_BOOLEAN (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* VOID:UINT,UINT,UINT (ags/object/ags_marshallers.list:9) */
extern
void ags_cclosure_marshal_VOID__UINT_UINT_UINT (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:UINT,UINT,UINT,UINT (ags/object/ags_marshallers.list:10) */
extern
void ags_cclosure_marshal_VOID__UINT_UINT_UINT_UINT (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:UINT,UINT,UINT,UINT,UINT (ags/object/ags_marshallers.list:11) */
extern
void ags_cclosure_marshal_VOID__UINT_UINT_UINT_UINT_UINT (GClosure     *closure,
                                                          GValue       *return_value,
                                                          guint         n_param_values,
                                                          const GValue *param_values,
                                                          gpointer      invocation_hint,
                                                          gpointer      marshal_data);

/* VOID:UINT,UINT,UINT,UINT,UINT,UINT (ags/object/ags_marshallers.list:12) */
extern
void ags_cclosure_marshal_VOID__UINT_UINT_UINT_UINT_UINT_UINT (GClosure     *closure,
                                                               GValue       *return_value,
                                                               guint         n_param_values,
                                                               const GValue *param_values,
                                                               gpointer      invocation_hint,
                                                               gpointer      marshal_data);

/* VOID:UINT,UINT,UINT,UINT,UINT,UINT,UINT (ags/object/ags_marshallers.list:13) */
extern
void ags_cclosure_marshal_VOID__UINT_UINT_UINT_UINT_UINT_UINT_UINT (GClosure     *closure,
                                                                    GValue       *return_value,
                                                                    guint         n_param_values,
                                                                    const GValue *param_values,
                                                                    gpointer      invocation_hint,
                                                                    gpointer      marshal_data);

/* VOID:UINT,DOUBLE,UINT (ags/object/ags_marshallers.list:14) */
extern
void ags_cclosure_marshal_VOID__UINT_DOUBLE_UINT (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:UINT,INT (ags/object/ags_marshallers.list:15) */
extern
void ags_cclosure_marshal_VOID__UINT_INT (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);

/* VOID:UINT,DOUBLE (ags/object/ags_marshallers.list:16) */
extern
void ags_cclosure_marshal_VOID__UINT_DOUBLE (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* VOID:UINT,STRING,UINT (ags/object/ags_marshallers.list:17) */
extern
void ags_cclosure_marshal_VOID__UINT_STRING_UINT (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:UINT,POINTER,UINT (ags/object/ags_marshallers.list:18) */
extern
void ags_cclosure_marshal_VOID__UINT_POINTER_UINT (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* VOID:INT64,UINT (ags/object/ags_marshallers.list:19) */
extern
void ags_cclosure_marshal_VOID__INT64_UINT (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:POINTER,UINT (ags/object/ags_marshallers.list:20) */
extern
void ags_cclosure_marshal_VOID__POINTER_UINT (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* VOID:POINTER,UINT,BOOLEAN (ags/object/ags_marshallers.list:21) */
extern
void ags_cclosure_marshal_VOID__POINTER_UINT_BOOLEAN (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:DOUBLE,DOUBLE (ags/object/ags_marshallers.list:22) */
extern
void ags_cclosure_marshal_VOID__DOUBLE_DOUBLE (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:POINTER,UINT,UINT (ags/object/ags_marshallers.list:23) */
extern
void ags_cclosure_marshal_VOID__POINTER_UINT_UINT (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* VOID:STRING,UINT (ags/object/ags_marshallers.list:24) */
extern
void ags_cclosure_marshal_VOID__STRING_UINT (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* VOID:STRING,UINT,DOUBLE (ags/object/ags_marshallers.list:25) */
extern
void ags_cclosure_marshal_VOID__STRING_UINT_DOUBLE (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* VOID:STRING,UINT,POINTER (ags/object/ags_marshallers.list:26) */
extern
void ags_cclosure_marshal_VOID__STRING_UINT_POINTER (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:STRING,UINT,STRING,DOUBLE (ags/object/ags_marshallers.list:27) */
extern
void ags_cclosure_marshal_VOID__STRING_UINT_STRING_DOUBLE (GClosure     *closure,
                                                           GValue       *return_value,
                                                           guint         n_param_values,
                                                           const GValue *param_values,
                                                           gpointer      invocation_hint,
                                                           gpointer      marshal_data);

/* VOID:STRING,POINTER (ags/object/ags_marshallers.list:28) */
extern
void ags_cclosure_marshal_VOID__STRING_POINTER (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:STRING,STRING,STRING (ags/object/ags_marshallers.list:29) */
extern
void ags_cclosure_marshal_VOID__STRING_STRING_STRING (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:POINTER,INT (ags/object/ags_marshallers.list:30) */
extern
void ags_cclosure_marshal_VOID__POINTER_INT (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* VOID:POINTER,INT,POINTER (ags/object/ags_marshallers.list:31) */
extern
void ags_cclosure_marshal_VOID__POINTER_INT_POINTER (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:POINTER,INT,INT,BOOLEAN (ags/object/ags_marshallers.list:32) */
extern
void ags_cclosure_marshal_VOID__POINTER_INT_INT_BOOLEAN (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* VOID:POINTER,POINTER (ags/object/ags_marshallers.list:34) */
extern
void ags_cclosure_marshal_VOID__POINTER_POINTER (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:POINTER,UINT,POINTER (ags/object/ags_marshallers.list:36) */
extern
void ags_cclosure_marshal_VOID__POINTER_UINT_POINTER (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:POINTER,POINTER,UINT (ags/object/ags_marshallers.list:37) */
extern
void ags_cclosure_marshal_VOID__POINTER_POINTER_UINT (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:POINTER,POINTER,POINTER (ags/object/ags_marshallers.list:38) */
extern
void ags_cclosure_marshal_VOID__POINTER_POINTER_POINTER (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* VOID:POINTER,STRING,STRING,STRING,INT (ags/object/ags_marshallers.list:39) */
extern
void ags_cclosure_marshal_VOID__POINTER_STRING_STRING_STRING_INT (GClosure     *closure,
                                                                  GValue       *return_value,
                                                                  guint         n_param_values,
                                                                  const GValue *param_values,
                                                                  gpointer      invocation_hint,
                                                                  gpointer      marshal_data);

/* VOID:POINTER,OBJECT,OBJECT,STRING,STRING,STRING,UINT,UINT,UINT,UINT,INT,UINT,UINT (ags/object/ags_marshallers.list:40) */
extern
void ags_cclosure_marshal_VOID__POINTER_OBJECT_OBJECT_STRING_STRING_STRING_UINT_UINT_UINT_UINT_INT_UINT_UINT (GClosure     *closure,
                                                                                                              GValue       *return_value,
                                                                                                              guint         n_param_values,
                                                                                                              const GValue *param_values,
                                                                                                              gpointer      invocation_hint,
                                                                                                              gpointer      marshal_data);

/* VOID:OBJECT,UINT (ags/object/ags_marshallers.list:41) */
extern
void ags_cclosure_marshal_VOID__OBJECT_UINT (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* VOID:OBJECT,UINT,UINT,UINT (ags/object/ags_marshallers.list:42) */
extern
void ags_cclosure_marshal_VOID__OBJECT_UINT_UINT_UINT (GClosure     *closure,
                                                       GValue       *return_value,
                                                       guint         n_param_values,
                                                       const GValue *param_values,
                                                       gpointer      invocation_hint,
                                                       gpointer      marshal_data);

/* VOID:OBJECT,OBJECT (ags/object/ags_marshallers.list:43) */
extern
void ags_cclosure_marshal_VOID__OBJECT_OBJECT (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:OBJECT,OBJECT,OBJECT,INT,BOOLEAN (ags/object/ags_marshallers.list:44) */
extern
void ags_cclosure_marshal_VOID__OBJECT_OBJECT_OBJECT_INT_BOOLEAN (GClosure     *closure,
                                                                  GValue       *return_value,
                                                                  guint         n_param_values,
                                                                  const GValue *param_values,
                                                                  gpointer      invocation_hint,
                                                                  gpointer      marshal_data);

/* VOID:OBJECT,OBJECT,OBJECT,OBJECT,OBJECT,OBJECT,UINT,INT,BOOLEAN (ags/object/ags_marshallers.list:45) */
extern
void ags_cclosure_marshal_VOID__OBJECT_OBJECT_OBJECT_OBJECT_OBJECT_OBJECT_UINT_INT_BOOLEAN (GClosure     *closure,
                                                                                            GValue       *return_value,
                                                                                            guint         n_param_values,
                                                                                            const GValue *param_values,
                                                                                            gpointer      invocation_hint,
                                                                                            gpointer      marshal_data);

/* VOID:OBJECT,OBJECT,OBJECT,OBJECT,OBJECT,OBJECT,OBJECT,OBJECT (ags/object/ags_marshallers.list:46) */
extern
void ags_cclosure_marshal_VOID__OBJECT_OBJECT_OBJECT_OBJECT_OBJECT_OBJECT_OBJECT_OBJECT (GClosure     *closure,
                                                                                         GValue       *return_value,
                                                                                         guint         n_param_values,
                                                                                         const GValue *param_values,
                                                                                         gpointer      invocation_hint,
                                                                                         gpointer      marshal_data);

/* POINTER:VOID (ags/object/ags_marshallers.list:47) */
extern
void ags_cclosure_marshal_POINTER__VOID (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* INT:VOID (ags/object/ags_marshallers.list:48) */
extern
void ags_cclosure_marshal_INT__VOID (GClosure     *closure,
                                     GValue       *return_value,
                                     guint         n_param_values,
                                     const GValue *param_values,
                                     gpointer      invocation_hint,
                                     gpointer      marshal_data);

/* INT64:OBJECT (ags/object/ags_marshallers.list:49) */
extern
void ags_cclosure_marshal_INT64__OBJECT (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* UINT:VOID (ags/object/ags_marshallers.list:50) */
extern
void ags_cclosure_marshal_UINT__VOID (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* BOOLEAN:VOID (ags/object/ags_marshallers.list:51) */
extern
void ags_cclosure_marshal_BOOLEAN__VOID (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* BOOLEAN:UINT,POINTER (ags/object/ags_marshallers.list:52) */
extern
void ags_cclosure_marshal_BOOLEAN__UINT_POINTER (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* BOOLEAN:POINTER,UINT (ags/object/ags_marshallers.list:53) */
extern
void ags_cclosure_marshal_BOOLEAN__POINTER_UINT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* BOOLEAN:OBJECT,OBJECT (ags/object/ags_marshallers.list:54) */
extern
void ags_cclosure_marshal_BOOLEAN__OBJECT_OBJECT (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* UINT:INT,UINT,POINTER (ags/object/ags_marshallers.list:55) */
extern
void ags_cclosure_marshal_UINT__INT_UINT_POINTER (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* DOUBLE:DOUBLE,BOOLEAN (ags/object/ags_marshallers.list:56) */
extern
void ags_cclosure_marshal_DOUBLE__DOUBLE_BOOLEAN (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* STRING:STRING,STRING (ags/object/ags_marshallers.list:57) */
extern
void ags_cclosure_marshal_STRING__STRING_STRING (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* STRING:POINTER,STRING,STRING,STRING,STRING,UINT,POINTER (ags/object/ags_marshallers.list:58) */
extern
void ags_cclosure_marshal_STRING__POINTER_STRING_STRING_STRING_STRING_UINT_POINTER (GClosure     *closure,
                                                                                    GValue       *return_value,
                                                                                    guint         n_param_values,
                                                                                    const GValue *param_values,
                                                                                    gpointer      invocation_hint,
                                                                                    gpointer      marshal_data);

/* POINTER:INT (ags/object/ags_marshallers.list:60) */
extern
void ags_cclosure_marshal_POINTER__INT (GClosure     *closure,
                                        GValue       *return_value,
                                        guint         n_param_values,
                                        const GValue *param_values,
                                        gpointer      invocation_hint,
                                        gpointer      marshal_data);

/* POINTER:UINT (ags/object/ags_marshallers.list:61) */
extern
void ags_cclosure_marshal_POINTER__UINT (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* POINTER:POINTER (ags/object/ags_marshallers.list:62) */
extern
void ags_cclosure_marshal_POINTER__POINTER (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* POINTER:INT,UINT (ags/object/ags_marshallers.list:63) */
extern
void ags_cclosure_marshal_POINTER__INT_UINT (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* POINTER:UINT,UINT (ags/object/ags_marshallers.list:64) */
extern
void ags_cclosure_marshal_POINTER__UINT_UINT (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* POINTER:UINT,POINTER (ags/object/ags_marshallers.list:65) */
extern
void ags_cclosure_marshal_POINTER__UINT_POINTER (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* POINTER:POINTER,POINTER,POINTER (ags/object/ags_marshallers.list:66) */
extern
void ags_cclosure_marshal_POINTER__POINTER_POINTER_POINTER (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);

/* POINTER:POINTER,UINT (ags/object/ags_marshallers.list:67) */
extern
void ags_cclosure_marshal_POINTER__POINTER_UINT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* POINTER:STRING,STRING (ags/object/ags_marshallers.list:68) */
extern
void ags_cclosure_marshal_POINTER__STRING_STRING (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* POINTER:STRING,STRING,STRING (ags/object/ags_marshallers.list:69) */
extern
void ags_cclosure_marshal_POINTER__STRING_STRING_STRING (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* POINTER:STRING,STRING,STRING,STRING (ags/object/ags_marshallers.list:70) */
extern
void ags_cclosure_marshal_POINTER__STRING_STRING_STRING_STRING (GClosure     *closure,
                                                                GValue       *return_value,
                                                                guint         n_param_values,
                                                                const GValue *param_values,
                                                                gpointer      invocation_hint,
                                                                gpointer      marshal_data);

/* POINTER:POINTER,POINTER,UINT (ags/object/ags_marshallers.list:71) */
extern
void ags_cclosure_marshal_POINTER__POINTER_POINTER_UINT (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* POINTER:POINTER,UINT,POINTER,POINTER (ags/object/ags_marshallers.list:72) */
extern
void ags_cclosure_marshal_POINTER__POINTER_UINT_POINTER_POINTER (GClosure     *closure,
                                                                 GValue       *return_value,
                                                                 guint         n_param_values,
                                                                 const GValue *param_values,
                                                                 gpointer      invocation_hint,
                                                                 gpointer      marshal_data);

/* POINTER:OBJECT (ags/object/ags_marshallers.list:73) */
extern
void ags_cclosure_marshal_POINTER__OBJECT (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* POINTER:OBJECT,POINTER,UINT (ags/object/ags_marshallers.list:74) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_POINTER_UINT (GClosure     *closure,
                                                        GValue       *return_value,
                                                        guint         n_param_values,
                                                        const GValue *param_values,
                                                        gpointer      invocation_hint,
                                                        gpointer      marshal_data);

/* POINTER:OBJECT,POINTER,INT64 (ags/object/ags_marshallers.list:75) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_POINTER_INT64 (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* POINTER:OBJECT,OBJECT (ags/object/ags_marshallers.list:76) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_OBJECT (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* POINTER:OBJECT,STRING,STRING,STRING,POINTER (ags/object/ags_marshallers.list:77) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_STRING_STRING_STRING_POINTER (GClosure     *closure,
                                                                        GValue       *return_value,
                                                                        guint         n_param_values,
                                                                        const GValue *param_values,
                                                                        gpointer      invocation_hint,
                                                                        gpointer      marshal_data);

/* POINTER:OBJECT,STRING,STRING,STRING,STRING,POINTER (ags/object/ags_marshallers.list:78) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_STRING_STRING_STRING_STRING_POINTER (GClosure     *closure,
                                                                               GValue       *return_value,
                                                                               guint         n_param_values,
                                                                               const GValue *param_values,
                                                                               gpointer      invocation_hint,
                                                                               gpointer      marshal_data);

/* POINTER:OBJECT,STRING,STRING,STRING,UINT,POINTER,POINTER (ags/object/ags_marshallers.list:79) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_STRING_STRING_STRING_UINT_POINTER_POINTER (GClosure     *closure,
                                                                                     GValue       *return_value,
                                                                                     guint         n_param_values,
                                                                                     const GValue *param_values,
                                                                                     gpointer      invocation_hint,
                                                                                     gpointer      marshal_data);

/* POINTER:OBJECT,STRING,STRING,STRING,STRING,UINT,POINTER,POINTER (ags/object/ags_marshallers.list:80) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_STRING_STRING_STRING_STRING_UINT_POINTER_POINTER (GClosure     *closure,
                                                                                            GValue       *return_value,
                                                                                            guint         n_param_values,
                                                                                            const GValue *param_values,
                                                                                            gpointer      invocation_hint,
                                                                                            gpointer      marshal_data);

/* POINTER:OBJECT,POINTER,OBJECT,STRING,STRING,STRING (ags/object/ags_marshallers.list:81) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_POINTER_OBJECT_STRING_STRING_STRING (GClosure     *closure,
                                                                               GValue       *return_value,
                                                                               guint         n_param_values,
                                                                               const GValue *param_values,
                                                                               gpointer      invocation_hint,
                                                                               gpointer      marshal_data);

/* POINTER:OBJECT,POINTER,OBJECT,POINTER,STRING,STRING,STRING (ags/object/ags_marshallers.list:82) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_POINTER_OBJECT_POINTER_STRING_STRING_STRING (GClosure     *closure,
                                                                                       GValue       *return_value,
                                                                                       guint         n_param_values,
                                                                                       const GValue *param_values,
                                                                                       gpointer      invocation_hint,
                                                                                       gpointer      marshal_data);

/* POINTER:OBJECT,POINTER,POINTER,OBJECT,STRING,STRING,STRING (ags/object/ags_marshallers.list:83) */
extern
void ags_cclosure_marshal_POINTER__OBJECT_POINTER_POINTER_OBJECT_STRING_STRING_STRING (GClosure     *closure,
                                                                                       GValue       *return_value,
                                                                                       guint         n_param_values,
                                                                                       const GValue *param_values,
                                                                                       gpointer      invocation_hint,
                                                                                       gpointer      marshal_data);

/* POINTER:POINTER,STRING,STRING (ags/object/ags_marshallers.list:84) */
extern
void ags_cclosure_marshal_POINTER__POINTER_STRING_STRING (GClosure     *closure,
                                                          GValue       *return_value,
                                                          guint         n_param_values,
                                                          const GValue *param_values,
                                                          gpointer      invocation_hint,
                                                          gpointer      marshal_data);

/* OBJECT:VOID (ags/object/ags_marshallers.list:85) */
extern
void ags_cclosure_marshal_OBJECT__VOID (GClosure     *closure,
                                        GValue       *return_value,
                                        guint         n_param_values,
                                        const GValue *param_values,
                                        gpointer      invocation_hint,
                                        gpointer      marshal_data);

/* OBJECT:UINT,POINTER (ags/object/ags_marshallers.list:86) */
extern
void ags_cclosure_marshal_OBJECT__UINT_POINTER (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* OBJECT:STRING,STRING,STRING (ags/object/ags_marshallers.list:87) */
extern
void ags_cclosure_marshal_OBJECT__STRING_STRING_STRING (GClosure     *closure,
                                                        GValue       *return_value,
                                                        guint         n_param_values,
                                                        const GValue *param_values,
                                                        gpointer      invocation_hint,
                                                        gpointer      marshal_data);

/* OBJECT:OBJECT (ags/object/ags_marshallers.list:88) */
extern
void ags_cclosure_marshal_OBJECT__OBJECT (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);

/* OBJECT:OBJECT,POINTER,POINTER (ags/object/ags_marshallers.list:89) */
extern
void ags_cclosure_marshal_OBJECT__OBJECT_POINTER_POINTER (GClosure     *closure,
                                                          GValue       *return_value,
                                                          guint         n_param_values,
                                                          const GValue *param_values,
                                                          gpointer      invocation_hint,
                                                          gpointer      marshal_data);

/* OBJECT:OBJECT,POINTER,POINTER,POINTER (ags/object/ags_marshallers.list:90) */
extern
void ags_cclosure_marshal_OBJECT__OBJECT_POINTER_POINTER_POINTER (GClosure     *closure,
                                                                  GValue       *return_value,
                                                                  guint         n_param_values,
                                                                  const GValue *param_values,
                                                                  gpointer      invocation_hint,
                                                                  gpointer      marshal_data);

/* OBJECT:OBJECT,OBJECT (ags/object/ags_marshallers.list:91) */
extern
void ags_cclosure_marshal_OBJECT__OBJECT_OBJECT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);


G_END_DECLS

#endif /* __AGS_CCLOSURE_MARSHAL_MARSHAL_H__ */
