name: C/C++ meson test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1
    - name: Set and install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq make gcc gettext meson ninja-build pkg-config gobject-introspection libgirepository1.0-dev libwebkit2gtk-4.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libinstpatch-dev libsndfile-dev libsamplerate-dev libxml2-dev ladspa-sdk dssi-dev lv2-dev fftw3-dev libasound2-dev libjack-jackd2-dev libpulse-dev uuid-dev gtk-doc-tools xvfb libcunit1-dev pulseaudio cmt swh-lv2 invada-studio-plugins-lv2 calf-plugins fluid-soundfont-gm hydrogen-drumkits libxtst-dev
    - name: meson
      run: mkdir build && cd build && meson --buildtype debug -Dalsa=true -Djack=true -Dpulse=true ..
    - name: ninja
      run: cd build && ninja
    - name: meson test
      run: cd build && xvfb-run --server-args="-screen 0 1920x1080x24" -a meson test -t 1000
