name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    - name: Set and install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install aptitude
	sudo DEBIAN_FRONTEND=noninteractive aptitude -y -f install
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -f make gcc gettext autoconf automake autopoint autotools-dev pkg-config gobject-introspection libgirepository1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-4-dev libinstpatch-dev libsndfile-dev libsamplerate-dev libxml2-dev libsoup-3.0-dev ladspa-sdk dssi-dev lv2-dev fftw3-dev libasound2-dev libjack-jackd2-dev libpulse-dev uuid-dev gtk-doc-tools xvfb libcunit1-dev
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: xvfb-run --server-args="-screen 0 1920x1080x24" -a make check
    - name: make distcheck
      run: xvfb-run --server-args="-screen 0 1920x1080x24" -a make distcheck
      env:
        DISTCHECK_CONFIGURE_FLAGS: --enable-introspection --disable-vst3
