name: C/C++ meson CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    - name: Set and install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get remove libunwind-14-dev
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -f make gcc gettext meson ninja-build pkg-config gobject-introspection libgirepository1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-4-dev libinstpatch-dev libsndfile-dev libsamplerate-dev libxml2-dev libsoup-3.0-dev ladspa-sdk dssi-dev lv2-dev fftw3-dev libasound2-dev libjack-jackd2-dev libpulse-dev libpoppler-glib-dev uuid-dev gtk-doc-tools xvfb libcunit1-dev
    - name: meson
      run: mkdir build && cd build && meson ..
    - name: ninja
      run: cd build && ninja
