name: GSequencer MSys2

on:
  push:
    # Publish `3.x.x` tags as releases.
    tags:
      - 3.*

env:
  IMAGE_NAME: gsequencer-msys2
  
jobs:
  push:
    runs-on: msys2
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v1

      - name: get version
        run: |
          set VERSION="${{ github.ref }}"

      - name: gsequencer-msys2
        uses: ./.github/actions/gsequencer-msys2
        with:
          version: "$VERSION"
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
