name: GSequencer MSys2

on:
  push:
    branches:
      - master

    # Publish `v3.x.x` tags as releases.
    tags:
      - 3.*

env:
  IMAGE_NAME: gsequencer-msys2

jobs:
  push:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v1

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password--stdin

      - name: get version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

      - name: gsequencer-msys2
        uses: ./.github/actions/gsequencer-msys2
        with:
          version: "$VERSION"
